## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('remote-mih-framework',['core', 'node', 'mobility', 'wifi'])
    obj.source = 'remote-mih-framework.cc'

